language: node_js
sudo: required
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
node_js: '6'
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
dist: trusty
env:
  global:
  - secure: mmcc6HIWjsZfL4UfpZw1qjxBjcfD5GSBDhXrA0oGKsDta2Pbg1VKcJWnfWZBCcInmksng3zpdSqkfiaZyHSKkJYQa1heZh7Q976aGsF4+mCSjjvwo4U400FNDr5xEQjf2RoC1acvT3yjWjfOeXDnWVaiq2louPsS+jFJCokidvOSo02PjW03j7gHqQbjNXfFD+gsKfPyZZM1YxiML/0QhgQ+MMCDdLbOHGVWuTw0mtqTCIHB2m6Og5ZGqZ/ORbHjLCDn6APeMsHVyC603cLQm0MyqT1V8/WzXC0aetaxQ8/PklaDHSiBZq1SVUkSZQcnjEyLp7aR2igVgQyoo/S5nhn8FMYZvrdcJxdoZlWzkCXN8C72xrnQSvlBEDViloePn8Pivh+sI1a6eg0xcyGgM8OaIoi1WwkBFRW6t3JY48bHzBctj2i9v7wvKzdtKbXlkDHbsVXW86aABzxW39vQjIZKNVffRcmNRzuQ0kC3vcYEU6LvqYv95r+pIf2PjncP7GXJVwzv95Y5YJGz1/W91QxdM8Wb2xOG/BYv0Mm1qVVLFzEK9vW1t9sgl9egjOmJRXLhCFG4FrivChVeBCqYiSWmsDlH9ofKkmcPiqsViScJATzKUyO9MLTVP+8EA+nRAlyLXgelT9HXBYNcOttkB8Iz718bsNeK3izwPqrNf1M=
  - secure: U+vd5ZEkRcOSb1WrGMtBfN/U/cbYoqs+rHM3EmiPuBdwVW8lt8l7WuRFTpJt4BtQgu4ouCoDDknE485CVK2jO50ZazjGOmTo4/WqO2DZLqD/6Of5VX6Q4CwuhsEoYsPrcFRm2J9tMP97C2z5H5KxZfZJUqaKvXpjPJ278+KN8QLaewzdT+kV1THzXn6yc6EacJUuNsqlvGjZ1x11MHqmSW9AhwMatsVOip7kuZogOiix2OjuLSZ0u2YEjxgJay1KujTLmgMh27l1paHyqSsIsKNT42/ckdxLChHcocXr3R4nLIiSlBIpZ1IKiazZpMdW8IkMTQ5O+Sa4oDqGxCNlSjfjO3abNHbsU78O/KSyqIk+aiK/6v8H71m/ctnZ8PetQUUk+sNtOltF96ii0mukHA0/wr0zmYuEHDwGb8Z3F4bxGNkP/yQQS3ZpFgmfqxoAYchY1fwsKTQvBdk6eoMO4baJb5xC/bu8FDUIQQs02UW6e7BWeJqX+whVCE91CM/ShHNRZwA3fblShX+7osuPeh8RQmdws3Eloa0tD9tX9MzgnjNDDkF8ywk+Dp/Thj3GLp2HSg/h9FAVNAfNR+UyS/1OY7fd6DEuJU12x+wY/12+BFvpvDcPy73Nagjaa+oJoN4TLFUFZh/Lxj68RsAeGUPq2B4bMrz0SpyoNyB+C8I=
